### ISSUE TITLE
iOS展示有问题

### ISSUE THREAD

**Issue by SoboioYan** [kivisense/wechat-kivicube-slam-plugin-api-demo#12]
1.3.18版本  iOS展示有问题   测试机型 iPhone Xs Pro Max 15.6.1

**Comment by listenlin** [comment]
说一下表现，或者给到截图、录屏等，展示具体是什么问题。

**Comment by SoboioYan** [comment]
![ba690cd3d81c8617b66e16a55b2aa21](https://user-images.githubusercontent.com/40989571/202336223-0b94ae05-ebd5-49f4-a990-0acf0167cbcd.jpg)
这是ios展示的  画面偏移  手势也没用了 
![291ee854f2ee44d3e75d7c82060d580](https://user-images.githubusercontent.com/40989571/202336305-b9ee7f09-f72d-4549-8330-2b9e57cb8ea4.jpg)
这是andriod 的展示

**Comment by listenlin** [comment]
没有问题的代码情况描述，我们也无从猜测做错了什么，或者我们插件哪里错了。

烦请提供一下可复现问题的代码片段吧。
