### ISSUE TITLE
当planeTracking= vertical时，无法旋转模型

### ISSUE THREAD

**Issue by zhihanhe** [kivisense/wechat-kivicube-slam-plugin-api-demo#4]
在下载demo后，想让牛排挂在墙上，发现牛排还是水平的，牛排是无法垂直于墙面的。请问：
1.如何判断水平还是垂直。
2.如果桌子是斜面如何让slam返回倾斜角度旋转，牛排也能更好的切合

**Comment by listenlin** [comment]
1. 需要支持v2版本的手机测试。并且组件主动打开v2，默认是v1。
2. 只支持水平和垂直面，不能斜面。

**Comment by zhihanhe** [comment]
请问一下V2的哪个参数判断当前的平面是水平还是垂直的？

**Comment by listenlin** [comment]
v2版本需要等待用户持手机扫描周围环境，直到系统检测到平面，此时kivicube-slam组件会触发addAnchors事件，才能知道平面是水平还是垂直。

判定方式，在addAnchors事件函数中，获取平面的transform变换矩阵。判定方式参考下面代码：

`<kivicube-slam version="v2" downgrade planeTracking="both" bind:addAnchors="addAnchors" />`

```js
Page({
  addAnchors({ detail: anchors }) {
    console.log("平面类型：", anchors[0].transform[5] >= 0.98 ? "水平" : "垂直");
  }
})
```
