### ISSUE TITLE
是否可以调整光源位置？

### ISSUE THREAD

**Issue by ttkrpink** [kivisense/wechat-kivicube-slam-plugin-api-demo#9]
放了一个模型在场景里面，貌似现在光源是在上方。我的材质自身不发光，导致我的模型比较暗。怎么调整光源的位置？

谢谢

**Comment by listenlin** [comment]
README.md文档中有写光照功能的链接，https://github.com/kivisense/wechat-kivicube-slam-plugin-api-demo/blob/master/pages/api/light/light.js

**Comment by ttkrpink** [comment]
> README.md文档中有写光照功能的链接，https://github.com/kivisense/wechat-kivicube-slam-plugin-api-demo/blob/master/pages/api/light/light.js

thanks，missed that
